dask:
  nameOverride: rapidsai
  fullnameOverride: rapidsai

  scheduler:
    name: scheduler
    image:
      repository: "rapidsai/rapidsai"
      tag: 0.15-cuda10.1-runtime-ubuntu18.04
      pullPolicy: IfNotPresent
      # See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      pullSecrets:
      #  - name: regcred
    replicas: 1
    serviceType: "ClusterIP"
    # serviceType: "NodePort"
    # serviceType: "LoadBalancer"
    servicePort: 8786
    resources: {}
    #  limits:
    #    cpu: 1.8
    #    memory: 6G
    #  requests:
    #    cpu: 1.8
    #    memory: 6G
    tolerations:
    - key: nvidia.com/gpu
      operator: Equal
      value: present
      effect: NoSchedule
    nodeSelector: {}
    affinity: {}

  webUI:
    name: webui
    servicePort: 8787
    ingress:
      enabled: false
      tls: false
      # secretName: rapidsai-dask-scheduler-tls
      hostname: dask-ui.rapidsai.example.com
      annotations:
      # kubernetes.io/ingress.class: "nginx"
      # secretName: my-tls-cert
      # kubernetes.io/tls-acme: "true"

  worker:
    name: worker
    image:
      repository: "rapidsai/rapidsai"
      tag: 0.15-cuda10.1-runtime-ubuntu18.04
      pullPolicy: IfNotPresent
      dask_worker: "dask-cuda-worker"
      pullSecrets:
      #  - name: regcred
    replicas: 3
    env:
    #  - name: MYVAR
    #    value: value
    resources:
      limits:
        cpu: 1
        memory: 3G
        nvidia.com/gpu: 1
      requests:
        cpu: 1
        memory: 3G
        nvidia.com/gpu: 1
    tolerations:
    - key: nvidia.com/gpu
      operator: Equal
      value: present
      effect: NoSchedule
    nodeSelector: {}
    affinity: {}

  jupyter:
    name: jupyter
    enabled: true
    image:
      repository: "rapidsai/rapidsai"
      tag: 0.15-cuda10.1-runtime-ubuntu18.04
      pullPolicy: IfNotPresent
      pullSecrets:
      #  - name: regcred
    replicas: 1
    serviceType: "ClusterIP"
    # serviceType: "NodePort"
    # serviceType: "LoadBalancer"
    servicePort: 80
    # This hash corresponds to the password 'rapidsai'
    password: 'sha1:56152965e045:3cd9a2065e78b4a4e46c2d6f35ddd0160fe5b94d'
    extraConfig: |-
      c.ServerProxy.host_whitelist = ["localhost", "127.0.0.1", "rapidsai-scheduler"]
      c.NotebookApp.allow_origin = '*'
    env:
     - name: DASK_DISTRIBUTED__DASHBOARD__LINK
       value: /proxy/rapidsai-scheduler:8787/status
     - name: JUPYTER_FG  # Run Jupyter as a daemon in the foreground
       value: "true"
    resources:
      limits:
        cpu: 2
        memory: 6G
        nvidia.com/gpu: 1
      requests:
        cpu: 2
        memory: 6G
        nvidia.com/gpu: 1
    tolerations:
    - key: nvidia.com/gpu
      operator: Equal
      value: present
      effect: NoSchedule
    nodeSelector: {}
    affinity: {}
    ingress:
      enabled: false
      tls: false
      # secretName: rapidsai-jupyter-tls
      hostname: jupyter.rapidsai.example.com
      annotations:
        # kubernetes.io/ingress.class: "nginx"
        # secretName: my-tls-cert
        # kubernetes.io/tls-acme: "true"
